import express from 'express';
import type { Request, Response } from 'express';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { zipSync } from 'fflate';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env if present and override placeholder values
try {
  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (match) {
        const key = match[1];
        let val = match[2] || '';
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        if (!process.env[key] || process.env[key]?.startsWith('MY_')) {
          process.env[key] = val.trim();
        }
      }
    }
  }
} catch {
  // ignore
}

const PORT = 3000;
const HOST = '0.0.0.0';
const STORAGE_DIR = path.join(__dirname, '.cloud_storage');
if (!fs.existsSync(STORAGE_DIR)) {
  fs.mkdirSync(STORAGE_DIR, { recursive: true });
}

// Helper to initialize Gemini SDK with required telemetry header
function getAi(customKey?: string): GoogleGenAI {
  const apiKey = (customKey || process.env.GEMINI_API_KEY || '').trim();
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      },
    },
  });
}

type CloudChapter = {
  id: string;
  index: number;
  title: string;
  text: string;
  words: number;
  estimatedMinutes: number;
  audioPath?: string;
  audioDuration?: number;
  hasAudio: boolean;
};

type CloudJob = {
  id: string;
  title: string;
  name: string;
  size: number;
  status: 'uploading' | 'processing' | 'ready' | 'generating_audio' | 'complete' | 'failed';
  pages: number;
  processingProgress: number;
  audioReady: number;
  ttsConfigured: boolean;
  ttsProvider: string;
  error?: string;
  chapters: CloudChapter[];
  createdAt: number;
  updatedAt: number;
};

// In-memory job registry backed by disk
const jobs = new Map<string, CloudJob>();
const uploadChunks = new Map<string, { totalParts: number; parts: Map<number, Buffer> }>();

function jobPath(jobId: string): string {
  return path.join(STORAGE_DIR, `job_${jobId}.json`);
}

function audioPathFor(jobId: string, chapterId: string): string {
  const dir = path.join(STORAGE_DIR, 'audio', jobId);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return path.join(dir, `${chapterId}.wav`);
}

function saveJobToDisk(job: CloudJob) {
  try {
    fs.writeFileSync(jobPath(job.id), JSON.stringify(job, null, 2), 'utf8');
  } catch (err) {
    console.error('Failed to save job to disk:', err);
  }
}

function loadJobsFromDisk() {
  try {
    const files = fs.readdirSync(STORAGE_DIR);
    for (const f of files) {
      if (f.startsWith('job_') && f.endsWith('.json')) {
        const raw = fs.readFileSync(path.join(STORAGE_DIR, f), 'utf8');
        const job = JSON.parse(raw) as CloudJob;
        // Verify audio file existence
        for (const ch of job.chapters) {
          const aPath = audioPathFor(job.id, ch.id);
          ch.hasAudio = fs.existsSync(aPath);
          if (ch.hasAudio) ch.audioPath = `/api/cloud/audio/${job.id}/${ch.id}`;
        }
        job.audioReady = job.chapters.filter(c => c.hasAudio).length;
        jobs.set(job.id, job);
      }
    }
  } catch (err) {
    console.warn('No previous cloud jobs loaded:', err);
  }
}

loadJobsFromDisk();

function countWords(str: string): number {
  return str.trim() ? str.trim().split(/\s+/).length : 0;
}

/**
 * Concatenates multiple WAV buffers generated by Gemini TTS into a single valid RIFF WAV buffer.
 */
function concatenateWavBuffers(buffers: Buffer[]): Buffer {
  if (buffers.length === 0) return Buffer.alloc(0);
  if (buffers.length === 1) return buffers[0];

  const first = buffers[0];
  if (first.length < 44) return Buffer.concat(buffers);

  let totalDataLength = 0;
  const pcmChunks: Buffer[] = [];
  for (const buf of buffers) {
    if (buf.length > 44) {
      const pcm = buf.subarray(44);
      pcmChunks.push(pcm);
      totalDataLength += pcm.length;
    }
  }

  const out = Buffer.alloc(44 + totalDataLength);
  first.copy(out, 0, 0, 44);
  out.writeUInt32LE(36 + totalDataLength, 4);
  out.writeUInt32LE(totalDataLength, 40);

  let offset = 44;
  for (const chunk of pcmChunks) {
    chunk.copy(out, offset);
    offset += chunk.length;
  }

  return out;
}

/**
 * Splits text into paragraphs suitable for TTS narration (1500-2500 chars per segment)
 */
function splitTextForTts(text: string, maxLen = 2200): string[] {
  const paragraphs = text.split(/\n\n+/).map(p => p.trim()).filter(Boolean);
  const chunks: string[] = [];
  let current = '';

  for (const p of paragraphs) {
    if ((current + '\n\n' + p).length <= maxLen) {
      current = current ? current + '\n\n' + p : p;
    } else {
      if (current) chunks.push(current);
      if (p.length > maxLen) {
        // Break sentences
        const sentences = p.match(/[^.!?…]+[.!?…]+|[^.!?…]+$/g) || [p];
        let sub = '';
        for (const s of sentences) {
          if ((sub + ' ' + s.trim()).length <= maxLen) {
            sub = sub ? sub + ' ' + s.trim() : s.trim();
          } else {
            if (sub) chunks.push(sub);
            sub = s.trim();
          }
        }
        if (sub) chunks.push(sub);
        current = '';
      } else {
        current = p;
      }
    }
  }
  if (current) chunks.push(current);
  return chunks.length ? chunks : [text.trim()];
}

/**
 * Synthesizes audio using Gemini 3.8 Flash Lite TTS (gemini-3.8-flash-lite-tts).
 * Parallelizes chunks with concurrency of 3 for fast throughput.
 */
async function synthesizeSpeech(text: string, voiceName = 'Kore', customKey?: string): Promise<Buffer> {
  const ai = getAi(customKey);
  const segments = splitTextForTts(text).filter(s => s.trim().length > 0);
  if (!segments.length) {
    segments.push(text.trim() || 'Chapitre sans texte.');
  }

  const BATCH_SIZE = 3;
  const wavBuffers: Buffer[] = new Array(segments.length);

  for (let i = 0; i < segments.length; i += BATCH_SIZE) {
    const chunkBatch = segments.slice(i, i + BATCH_SIZE);
    const results = await Promise.all(
      chunkBatch.map(async (segment) => {
        const response = await ai.models.generateContent({
          model: 'gemini-3.8-flash-lite-tts',
          contents: [
            {
              role: 'user',
              parts: [
                {
                  text: segment,
                  speechMetadata: {
                    style: 'Narration de livre audio naturelle, fluide, chaleureuse et captivante en français.',
                  },
                },
              ],
            },
          ],
          config: {
            responseModalities: ['AUDIO'],
            speechConfig: {
              voiceConfig: {
                prebuiltVoiceConfig: { voiceName: voiceName || 'Kore' },
              },
            },
          },
        });

        const candidate = response.candidates?.[0];
        const audioPart = candidate?.content?.parts?.find(p => p.inlineData && p.inlineData.data);
        if (!audioPart?.inlineData?.data) {
          throw new Error('Gemini TTS n’a renvoyé aucun audio pour ce segment.');
        }

        return Buffer.from(audioPart.inlineData.data, 'base64');
      })
    );

    for (let j = 0; j < results.length; j++) {
      wavBuffers[i + j] = results[j];
    }
  }

  return concatenateWavBuffers(wavBuffers);
}

/**
 * Extracts and structures book chapters using Gemini 3.8 Flash (gemini-3.8-flash)
 */
async function extractBookFromPdf(pdfBuffer: Buffer, fileName: string): Promise<{ bookTitle: string; chapters: Array<{ title: string; text: string }> }> {
  const ai = getAi();
  const base64Pdf = pdfBuffer.toString('base64');

  const prompt = `Tu es un expert éditeur de livres audio et analyste littéraire.
Analyse ce document PDF et transforme-le en une structure de livre audio complète et propre.

Règles de découpage et de nettoyage:
1. Identifie le titre principal de l'œuvre.
2. Découpe le texte en chapitres logiques et cohérents (ex: Chapitre 1 — Le départ, Chapitre 2 — ..., Prologue, etc.). Si le document est un article ou court récit, crée 1 à 3 sections pertinentes.
3. Pour chaque chapitre, fournis le texte intégral destiné à être écouté:
   - Supprime les en-têtes et pieds de page répétés, les numéros de page orphelins, les césures de mots ("par- exemple" -> "par exemple").
   - Conserve l'intégralité du contenu narratif sans le résumer.
4. Réponds UNIQUEMENT par un objet JSON valide conforme à cette structure exacte:
{
  "bookTitle": "Titre du livre",
  "chapters": [
    {
      "title": "Nom du chapitre",
      "text": "Texte narratif intégral de ce chapitre à lire à voix haute..."
    }
  ]
}`;

  const response = await ai.models.generateContent({
    model: 'gemini-3.8-flash',
    contents: [
      {
        inlineData: {
          mimeType: 'application/pdf',
          data: base64Pdf,
        },
      },
      {
        text: prompt,
      },
    ],
    config: {
      responseMimeType: 'application/json',
    },
  });

  const responseText = response.text || '';
  try {
    const parsed = JSON.parse(responseText.trim());
    if (parsed && Array.isArray(parsed.chapters) && parsed.chapters.length > 0) {
      return {
        bookTitle: parsed.bookTitle || fileName.replace(/\.pdf$/i, ''),
        chapters: parsed.chapters,
      };
    }
  } catch (err) {
    console.warn('Failed to parse JSON response from Gemini Flash:', err, responseText);
  }

  // Fallback if parsing failed
  return {
    bookTitle: fileName.replace(/\.pdf$/i, ''),
    chapters: [
      {
        title: 'Chapitre 1 — Lecture intégrale',
        text: responseText.slice(0, 5000) || 'Contenu extrait du document.',
      },
    ],
  };
}

async function startServer() {
  const app = express();

  app.use(express.json({ limit: '65mb' }));
  app.use(express.urlencoded({ extended: true, limit: '65mb' }));

  // Cross-Origin isolation for WebAssembly SIMD and Workers
  app.use((_req, res, next) => {
    res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
    res.setHeader('Cross-Origin-Embedder-Policy', 'credentialless');
    next();
  });

  // Capabilities API
  app.get('/api/cloud/capabilities', (_req: Request, res: Response) => {
    const hasKey = Boolean(process.env.GEMINI_API_KEY);
    res.json({
      cloud: true,
      mode: '100% Cloud Gemini Flash',
      ttsConfigured: hasKey,
      ttsProvider: 'gemini-3.8-flash-lite-tts',
      textModel: 'gemini-3.8-flash',
      chunkUpload: true,
      ocr: true,
      voices: [
        { id: 'Kore', name: 'Kore (Voix féminine claire et douce)', gender: 'female' },
        { id: 'Puck', name: 'Puck (Voix masculine expressive et rythmée)', gender: 'male' },
        { id: 'Zephyr', name: 'Zephyr (Voix calme, chaleureuse et équilibrée)', gender: 'neutral' },
        { id: 'Charon', name: 'Charon (Voix grave, posée et narrative)', gender: 'male' },
        { id: 'Fenrir', name: 'Fenrir (Voix dynamique et affirmée)', gender: 'male' },
      ],
    });
  });

  // Standard health check used by frontend isRemoteTtsAvailable
  app.get('/api/health', (_req: Request, res: Response) => {
    res.json({
      ok: true,
      provider: process.env.GEMINI_API_KEY ? 'gemini' : 'local-fallback',
      ttsConfigured: Boolean(process.env.GEMINI_API_KEY),
      model: process.env.GEMINI_TTS_MODEL || 'gemini-3.8-flash-lite-tts',
    });
  });

  // Direct TTS endpoint used by frontend synthesizeRemoteChunk
  app.post('/api/tts', async (req: Request, res: Response) => {
    try {
      const body = req.body || {};
      const customKey =
        (req.headers['x-gemini-api-key'] as string) ||
        (body.apiKey as string) ||
        process.env.GEMINI_API_KEY;

      if (!customKey) {
        return res.status(503).json({
          error: 'Gemini n’est pas configuré. Variable GEMINI_API_KEY manquante.',
        });
      }
      const text = typeof body.text === 'string' ? body.text.trim() : '';
      if (!text) {
        return res.status(400).json({ error: 'Texte vide.' });
      }

      const voice = body.voice || process.env.GEMINI_TTS_VOICE || 'Kore';
      const model = body.model || process.env.GEMINI_TTS_MODEL || 'gemini-3.8-flash-lite-tts';
      const wavBuffer = await synthesizeSpeech(text, voice, customKey);

      res.json({
        audio: wavBuffer.toString('base64'),
        mimeType: 'audio/wav',
        model,
        voice,
      });
    } catch (err: any) {
      console.error('Erreur /api/tts:', err);
      const isQuota =
        err?.message?.includes('429') ||
        err?.message?.includes('RESOURCE_EXHAUSTED') ||
        err?.message?.includes('quota') ||
        err?.status === 429;
      res.status(isQuota ? 429 : 500).json({
        error: isQuota
          ? 'Quota Gemini Free Tier atteint. Bascule automatique sur la synthèse vocale locale.'
          : err?.message || 'Erreur synthèse vocale Gemini.',
        isQuota,
      });
    }
  });

  // List all books stored in cloud
  app.get('/api/cloud/books', (_req: Request, res: Response) => {
    const list = Array.from(jobs.values()).map(job => ({
      id: job.id,
      title: job.title,
      name: job.name,
      size: job.size,
      status: job.status,
      pages: job.pages,
      processingProgress: job.processingProgress,
      audioReady: job.chapters.filter(c => c.hasAudio).length,
      totalChapters: job.chapters.length,
      chapters: job.chapters.map(c => ({
        id: c.id,
        index: c.index,
        title: c.title,
        text: c.text,
        words: c.words,
        estimatedMinutes: c.estimatedMinutes,
        hasAudio: c.hasAudio,
        audioUrl: c.hasAudio ? `/api/cloud/audio/${job.id}/${c.id}` : undefined,
      })),
      createdAt: job.createdAt,
      updatedAt: job.updatedAt,
    }));
    res.json(list);
  });

  // Direct upload of PDF in base64
  app.post('/api/cloud/upload', async (req: Request, res: Response) => {
    try {
      const { name, title, base64Pdf } = req.body as { name?: string; title?: string; base64Pdf?: string };
      if (!base64Pdf) {
        return res.status(400).json({ error: 'Fichier PDF manquant dans la requête.' });
      }

      const jobId = crypto.randomUUID();
      const pdfBuffer = Buffer.from(base64Pdf, 'base64');
      const job: CloudJob = {
        id: jobId,
        title: title || name?.replace(/\.pdf$/i, '') || 'Livre sans titre',
        name: name || 'livre.pdf',
        size: pdfBuffer.length,
        status: 'processing',
        pages: 1,
        processingProgress: 20,
        audioReady: 0,
        ttsConfigured: Boolean(process.env.GEMINI_API_KEY),
        ttsProvider: 'gemini-3.8-flash-lite-tts',
        chapters: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
      };
      jobs.set(jobId, job);
      saveJobToDisk(job);

      // Async process in background
      void (async () => {
        try {
          job.processingProgress = 40;
          saveJobToDisk(job);

          const result = await extractBookFromPdf(pdfBuffer, job.name);
          job.title = result.bookTitle || job.title;
          job.chapters = result.chapters.map((ch, idx) => ({
            id: `ch-${idx + 1}`,
            index: idx,
            title: ch.title,
            text: ch.text,
            words: countWords(ch.text),
            estimatedMinutes: Math.max(1, Math.round(countWords(ch.text) / 150)),
            hasAudio: false,
          }));

          job.pages = Math.max(1, job.chapters.length);
          job.status = 'ready';
          job.processingProgress = 100;
          job.updatedAt = Date.now();
          saveJobToDisk(job);
        } catch (err: any) {
          console.error('Extraction error:', err);
          job.status = 'failed';
          job.error = err?.message || 'Erreur lors de l’analyse du PDF par Gemini Flash.';
          job.updatedAt = Date.now();
          saveJobToDisk(job);
        }
      })();

      res.json({ id: jobId, status: 'processing' });
    } catch (err: any) {
      res.status(500).json({ error: err?.message || 'Erreur d’envoi cloud' });
    }
  });

  // Chunked upload creation
  app.post('/api/cloud/jobs', (req: Request, res: Response) => {
    const { name, title, size } = req.body as { name?: string; title?: string; size?: number };
    if (!name || !size || size <= 0) {
      return res.status(400).json({ error: 'Fichier PDF invalide.' });
    }

    const chunkSize = 2 * 1024 * 1024;
    const totalParts = Math.ceil(size / chunkSize);
    const jobId = crypto.randomUUID();

    const job: CloudJob = {
      id: jobId,
      title: title || name.replace(/\.pdf$/i, ''),
      name,
      size,
      status: 'uploading',
      pages: 1,
      processingProgress: 0,
      audioReady: 0,
      ttsConfigured: Boolean(process.env.GEMINI_API_KEY),
      ttsProvider: 'gemini-3.8-flash-lite-tts',
      chapters: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    };

    jobs.set(jobId, job);
    uploadChunks.set(jobId, { totalParts, parts: new Map() });
    res.json({ id: jobId, chunkSize, totalParts });
  });

  // Chunked upload slice
  app.post('/api/cloud/jobs/:id/chunk', (req: Request, res: Response) => {
    const { id } = req.params;
    const { index, data } = req.body as { index?: number; data?: string };

    const chunkData = uploadChunks.get(id);
    if (!chunkData || typeof index !== 'number' || !data) {
      return res.status(400).json({ error: 'Bloc manquant ou invalide.' });
    }

    const buf = Buffer.from(data, 'base64');
    chunkData.parts.set(index, buf);
    res.json({ ok: true, index });
  });

  // Chunked upload complete
  app.post('/api/cloud/jobs/:id/complete', (req: Request, res: Response) => {
    const { id } = req.params;
    const job = jobs.get(id);
    const chunkData = uploadChunks.get(id);

    if (!job || !chunkData) {
      return res.status(404).json({ error: 'Tâche cloud introuvable.' });
    }

    if (chunkData.parts.size < chunkData.totalParts) {
      return res.status(400).json({ error: 'Tous les blocs du document n’ont pas été reçus.' });
    }

    const sortedBuffers: Buffer[] = [];
    for (let i = 0; i < chunkData.totalParts; i += 1) {
      const part = chunkData.parts.get(i);
      if (!part) return res.status(400).json({ error: `Bloc ${i} manquant.` });
      sortedBuffers.push(part);
    }
    const fullBuffer = Buffer.concat(sortedBuffers);
    uploadChunks.delete(id);

    job.status = 'processing';
    job.processingProgress = 25;
    saveJobToDisk(job);

    void (async () => {
      try {
        job.processingProgress = 45;
        saveJobToDisk(job);

        const result = await extractBookFromPdf(fullBuffer, job.name);
        job.title = result.bookTitle || job.title;
        job.chapters = result.chapters.map((ch, idx) => ({
          id: `ch-${idx + 1}`,
          index: idx,
          title: ch.title,
          text: ch.text,
          words: countWords(ch.text),
          estimatedMinutes: Math.max(1, Math.round(countWords(ch.text) / 150)),
          hasAudio: false,
        }));

        job.pages = Math.max(1, job.chapters.length);
        job.status = 'ready';
        job.processingProgress = 100;
        job.updatedAt = Date.now();
        saveJobToDisk(job);
      } catch (err: any) {
        console.error('Cloud processing error:', err);
        job.status = 'failed';
        job.error = err?.message || 'Erreur lors de l’analyse du PDF.';
        job.updatedAt = Date.now();
        saveJobToDisk(job);
      }
    })();

    res.json({ ok: true, status: 'processing' });
  });

  // Get job details
  app.get('/api/cloud/jobs/:id', (req: Request, res: Response) => {
    const job = jobs.get(req.params.id);
    if (!job) return res.status(404).json({ error: 'Livre cloud introuvable.' });

    // Update hasAudio flags
    for (const ch of job.chapters) {
      const aPath = audioPathFor(job.id, ch.id);
      ch.hasAudio = fs.existsSync(aPath);
      if (ch.hasAudio) ch.audioPath = `/api/cloud/audio/${job.id}/${ch.id}`;
    }
    job.audioReady = job.chapters.filter(c => c.hasAudio).length;

    res.json({
      id: job.id,
      title: job.title,
      name: job.name,
      size: job.size,
      status: job.status,
      pages: job.pages,
      processingProgress: job.processingProgress,
      audioReady: job.audioReady,
      ttsConfigured: Boolean(process.env.GEMINI_API_KEY),
      ttsProvider: 'gemini-3.8-flash-lite-tts',
      error: job.error,
      chapters: job.chapters.map(c => ({
        id: c.id,
        index: c.index,
        title: c.title,
        text: c.text,
        words: c.words,
        estimatedMinutes: c.estimatedMinutes,
        hasAudio: c.hasAudio,
        audioUrl: c.hasAudio ? `/api/cloud/audio/${job.id}/${c.id}` : undefined,
      })),
    });
  });

  // Trigger TTS audio generation for a chapter or next pending chapter
  app.post('/api/cloud/jobs/:id/generate-audio', async (req: Request, res: Response) => {
    const job = jobs.get(req.params.id);
    if (!job) return res.status(404).json({ error: 'Livre cloud introuvable.' });

    const { chapterId, voiceName } = req.body as { chapterId?: string; voiceName?: string };
    let targetChapter: CloudChapter | undefined;

    if (chapterId) {
      targetChapter = job.chapters.find(c => c.id === chapterId);
    } else {
      targetChapter = job.chapters.find(c => !c.hasAudio);
    }

    if (!targetChapter) {
      return res.json({ complete: true, message: 'Tous les chapitres audio sont déjà générés.' });
    }

    try {
      job.status = 'generating_audio';
      const audioBuffer = await synthesizeSpeech(targetChapter.text, voiceName || 'Kore');
      const outFile = audioPathFor(job.id, targetChapter.id);
      fs.writeFileSync(outFile, audioBuffer);

      targetChapter.hasAudio = true;
      targetChapter.audioPath = `/api/cloud/audio/${job.id}/${targetChapter.id}`;
      targetChapter.audioDuration = Math.round(audioBuffer.length / (24000 * 2)); // 24kHz 16-bit mono

      job.audioReady = job.chapters.filter(c => c.hasAudio).length;
      job.status = job.audioReady >= job.chapters.length ? 'complete' : 'ready';
      job.updatedAt = Date.now();
      saveJobToDisk(job);

      res.json({
        ok: true,
        chapterId: targetChapter.id,
        audioUrl: targetChapter.audioPath,
        audioReady: job.audioReady,
        totalChapters: job.chapters.length,
      });
    } catch (err: any) {
      console.error('Audio generation error:', err);
      job.status = 'ready';
      saveJobToDisk(job);
      res.status(500).json({ error: err?.message || 'Erreur lors de la synthèse vocale Gemini Flash.' });
    }
  });

  // Compatibility endpoint for /tts-next
  app.post('/api/cloud/jobs/:id/tts-next', async (req: Request, res: Response) => {
    const job = jobs.get(req.params.id);
    if (!job) return res.status(404).json({ error: 'Livre cloud introuvable.' });

    const pending = job.chapters.find(c => !c.hasAudio);
    if (!pending) {
      job.status = 'complete';
      return res.json({ id: job.id, status: 'complete', audioReady: job.chapters.length });
    }

    try {
      const voice = (req.body as { voice?: string })?.voice || 'Kore';
      const audioBuffer = await synthesizeSpeech(pending.text, voice);
      const outFile = audioPathFor(job.id, pending.id);
      fs.writeFileSync(outFile, audioBuffer);
      pending.hasAudio = true;
      pending.audioPath = `/api/cloud/audio/${job.id}/${pending.id}`;
      job.audioReady = job.chapters.filter(c => c.hasAudio).length;
      job.status = job.audioReady >= job.chapters.length ? 'complete' : 'ready';
      saveJobToDisk(job);

      res.json({
        id: job.id,
        status: job.status,
        audioReady: job.audioReady,
        chapters: job.chapters.map(c => ({
          ...c,
          audioUrl: c.hasAudio ? `/api/cloud/audio/${job.id}/${c.id}` : undefined,
        })),
      });
    } catch (err: any) {
      res.status(500).json({ error: err?.message || 'Synthèse audio cloud impossible.' });
    }
  });

  // Stream WAV audio file with byte-range support
  app.get('/api/cloud/audio/:jobId/:chapterId', (req: Request, res: Response) => {
    const { jobId, chapterId } = req.params;
    const filePath = audioPathFor(jobId, chapterId.replace(/\.wav$/i, ''));

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ error: 'Fichier audio non disponible.' });
    }

    const stat = fs.statSync(filePath);
    const range = req.headers.range;

    if (range) {
      const parts = range.replace(/bytes=/, '').split('-');
      const start = parseInt(parts[0], 10);
      const end = parts[1] ? parseInt(parts[1], 10) : stat.size - 1;
      const chunkSize = end - start + 1;

      res.writeHead(206, {
        'Content-Range': `bytes ${start}-${end}/${stat.size}`,
        'Accept-Ranges': 'bytes',
        'Content-Length': chunkSize,
        'Content-Type': 'audio/wav',
      });
      fs.createReadStream(filePath, { start, end }).pipe(res);
    } else {
      res.writeHead(200, {
        'Content-Length': stat.size,
        'Content-Type': 'audio/wav',
        'Accept-Ranges': 'bytes',
      });
      fs.createReadStream(filePath).pipe(res);
    }
  });

  // Export full book ZIP
  app.get('/api/cloud/export/:jobId', (req: Request, res: Response) => {
    const job = jobs.get(req.params.jobId);
    if (!job) return res.status(404).json({ error: 'Livre introuvable.' });

    const entries: Record<string, Uint8Array> = {};
    for (const ch of job.chapters) {
      const fPath = audioPathFor(job.id, ch.id);
      if (fs.existsSync(fPath)) {
        const num = String(ch.index + 1).padStart(2, '0');
        const safeTitle = ch.title.replace(/[^\w\s-]/gi, '').trim() || `Chapitre_${ch.index + 1}`;
        entries[`${num} - ${safeTitle}.wav`] = new Uint8Array(fs.readFileSync(fPath));
      }
    }

    if (Object.keys(entries).length === 0) {
      return res.status(400).json({ error: 'Aucun chapitre audio n’a encore été généré pour ce livre.' });
    }

    const zipped = zipSync(entries, { level: 0 });
    const buffer = Buffer.from(zipped);

    res.writeHead(200, {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${encodeURIComponent(job.title)}.zip"`,
      'Content-Length': buffer.length,
    });
    res.end(buffer);
  });

  // Delete book and associated audio
  app.delete('/api/cloud/jobs/:id', (req: Request, res: Response) => {
    const { id } = req.params;
    jobs.delete(id);
    try {
      const fPath = jobPath(id);
      if (fs.existsSync(fPath)) fs.unlinkSync(fPath);
      const audioDir = path.join(STORAGE_DIR, 'audio', id);
      if (fs.existsSync(audioDir)) fs.rmSync(audioDir, { recursive: true, force: true });
    } catch (e) {
      console.warn('Error deleting job files:', e);
    }
    res.json({ ok: true, deleted: true });
  });

  // Create demo book
  app.post('/api/cloud/demo', (_req: Request, res: Response) => {
    const jobId = 'demo-carnet-bleu';
    const demoJob: CloudJob = {
      id: jobId,
      title: 'Le carnet bleu — Démo Cloud',
      name: 'le-carnet-bleu-demo.pdf',
      size: 45000,
      status: 'ready',
      pages: 3,
      processingProgress: 100,
      audioReady: 0,
      ttsConfigured: Boolean(process.env.GEMINI_API_KEY),
      ttsProvider: 'gemini-3.8-flash-lite-tts',
      chapters: [
        {
          id: 'demo-ch-1',
          index: 0,
          title: 'Chapitre 1 — La porte entrouverte',
          text: `Il était un peu plus de sept heures lorsque Noé aperçut la lumière sous la porte de l'atelier. D'habitude, la pièce restait fermée jusqu'au samedi. Ce matin-là, pourtant, quelqu'un avait laissé la clé dans la serrure.

Il poussa doucement. Sur la grande table, un carnet bleu attendait, ouvert à une page couverte d'une écriture minuscule. Au centre, une phrase était entourée trois fois : « Écoute avant de chercher à comprendre. »

Noé sourit. Cela ressemblait exactement au genre d'énigme que son grand-père aimait lui laisser.`,
          words: 92,
          estimatedMinutes: 1,
          hasAudio: false,
        },
        {
          id: 'demo-ch-2',
          index: 1,
          title: 'Chapitre 2 — Une voix dans le casque',
          text: `Dans le tiroir du bureau, il trouva un vieux casque audio relié à un petit lecteur. Une seule piste était disponible. Il appuya sur lecture et reconnut immédiatement la voix calme de son grand-père.

« Si tu entends ceci, c'est que tu as trouvé le carnet. Ne cours pas. Regarde autour de toi. Chaque détail compte davantage que la vitesse. »

Noé se retourna. Sur le mur, les cartes, les photographies et les notes semblaient soudain former un chemin.`,
          words: 85,
          estimatedMinutes: 1,
          hasAudio: false,
        },
        {
          id: 'demo-ch-3',
          index: 2,
          title: 'Chapitre 3 — Le premier indice',
          text: `Derrière une photographie du port, une enveloppe avait été glissée dans le cadre. À l'intérieur se trouvait une petite carte avec trois mots : bibliothèque, horloge, midi.

Cette fois, Noé ne chercha pas à deviner trop vite. Il rangea soigneusement le carnet dans son sac, remit le casque à sa place et sortit de l'atelier.

Le mystère pouvait commencer.`,
          words: 64,
          estimatedMinutes: 1,
          hasAudio: false,
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    };

    // Check if audio exists
    for (const ch of demoJob.chapters) {
      const aPath = audioPathFor(jobId, ch.id);
      ch.hasAudio = fs.existsSync(aPath);
      if (ch.hasAudio) ch.audioPath = `/api/cloud/audio/${jobId}/${ch.id}`;
    }
    demoJob.audioReady = demoJob.chapters.filter(c => c.hasAudio).length;

    jobs.set(jobId, demoJob);
    saveJobToDisk(demoJob);

    res.json({
      id: demoJob.id,
      title: demoJob.title,
      chapters: demoJob.chapters,
    });
  });

  // Export entire codebase as ZIP file
  app.get('/api/export-project-zip', (_req: Request, res: Response) => {
    try {
      const zipEntries: Record<string, Uint8Array> = {};
      const ignoreDirs = new Set(['node_modules', '.git', 'dist', '.cloud_storage', '.aistudio']);

      function addDirRecursive(currentDir: string, relPath = '') {
        const entries = fs.readdirSync(currentDir, { withFileTypes: true });
        for (const entry of entries) {
          if (ignoreDirs.has(entry.name)) continue;
          if (entry.name.endsWith('.zip')) continue;
          const full = path.join(currentDir, entry.name);
          const rel = relPath ? `${relPath}/${entry.name}` : entry.name;
          if (entry.isDirectory()) {
            addDirRecursive(full, rel);
          } else if (entry.isFile()) {
            const buf = fs.readFileSync(full);
            zipEntries[rel] = new Uint8Array(buf);
          }
        }
      }

      addDirRecursive(__dirname);
      const zipped = zipSync(zipEntries, { level: 6 });
      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', 'attachment; filename="livrevox-cloud-source.zip"');
      res.send(Buffer.from(zipped));
    } catch (err: any) {
      res.status(500).json({ error: err?.message || 'Erreur création ZIP' });
    }
  });

  // Vite in dev mode or static files in production
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(__dirname, 'dist')));
    app.get('*', (_req: Request, res: Response) => {
      res.sendFile(path.join(__dirname, 'dist', 'index.html'));
    });
  }

  app.listen(PORT, HOST, () => {
    console.log(`[LivreVox Cloud] Serveur actif sur http://${HOST}:${PORT}`);
  });
}

startServer().catch(err => {
  console.error('Failed to start server:', err);
  process.exit(1);
});
